name: # cjdns
version: # 19.1
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor: Vendor <kylerschin@gmail.com>
summary: # Public Key cryptography Ipv6 Decentralized Mesh Network
description: # Cjdns implements an encrypted IPv6 network using public-key cryptography for address allocation and a distributed hash table for routing. This provides near-zero-configuration networking, and prevents many of the security and scalability issues that plague existing networks.
icon: # 

parts:
  cjdns:

